<!DOCTYPE html>
<html>
<head>    
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="../../css/adminDashboard.css">
	<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <title>Document</title>
    
    <!-- Font Awesome JS -->
	<script src="https://use.fontawesome.com/e8115dfc1a.js"></script>
</head>
<body class="body-background">


<div class="wrapper ">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
		<img src="images/pngegg3.png" width="460" height="345">
		<div class="text-center bg-primary card mg-auto " style="width: 16rem; color: white;">Admin</div>
            </div>

            <ul class="list-unstyled components text-center">
                <li class="sidebarhov">
                    <a href="../Views/dashboard.phtml">
						<i class="fa fa-bar-chart" aria-hidden="true"></i> Home</a>
                </li>
				<li class="sidebarhov">
                    <a href="../Views/dashboard.phtml"> 
						  <i class="fa fa-user" aria-hidden="true"></i> Users</a>
                </li>
				<li class="sidebarhov">
                    <a href="../Views/dashboard.phtml"><i class="fa fa-cog" aria-hidden="true"></i> Create Experiments</a>
                </li>
				<li class="sidebarhov">
                    <a href="../Views/dashboard.phtml"><i class="fa fa-flask" aria-hidden="true"></i> Experiments</a>
                </li>
            </ul>
			<ul class="list-unstyled components text-center ">
                <li>
                    <a href="logoutAdmin.php" class="sidebarhov" >Log Out</a>
                </li>
            </ul>
        </nav>

        <!-- Page Content  -->
<div id="content">






<div class="header body-background3">
<div class="d-flex justify-content-between">
    <div class="p-2 align-self-center">
<button type="button" id="sidebarCollapse" class="sidebutton-hover sidebutton">
                        <i class="fa fa-align-left"></i>
                        <span>Menu</span>
                    </button></div>
    <div class="p-2 align-self-center">
<a class="dashboard" >Admin Panel</a></div>
    <div class="p-2 align-self-center">
	 </div>
  </div>
</div>




<div class="row ml-3 mr-3">
	
<div class="col">
<div class="dashboard2"> <a><i class="fa fa-area-chart" aria-hidden="true"></i></a> Statistics</div>
</div>
</div>


<div class="row ml-3 mr-3">
	<div class="col">
	  
	  <div class="container py-4">
		  <article class="postcard green3 green">
			  <div class="postcard__text ">
				  <h1 class="postcard__title green "><a href="#">USERS</a></h1>
				  <div class="postcard__bar"></div>
				  <p class="head-1">Users</p>
            		<p class="number"> <?php echo $usersCount ?> Total users</p>
            		<!-- <i class="fa fa-line-chart box-icon"></i> -->
			  </div>
		  </article></div></div>
	  <div class="col">


	  <div class="container py-4">
		  <article class="postcard red3 red">
			  <div class="postcard__text ">
				  <h1 class="postcard__title green "><a href="#">SURVEYS</a></h1>
				  <div class="postcard__bar"></div>
				  <p class="head-1">Surveys</p>
            		<p class="number"><?php echo $surveysCount ?> Total Surveys</p>
            		<!-- <i class="fa fa-line-chart box-icon"></i> -->
			  </div>
		  </article></div></div>
	  <div class="col">


	  <div class="container py-4">
		  <article class="postcard blue3 blue">
			  <div class="postcard__text ">
				  <h1 class="postcard__title green "><a href="#">POLLS</a></h1>
				  <div class="postcard__bar"></div>
				  <p class="head-1">Polls</p>
            		<p class="number"><?php echo $pollsCount ?> Total Polls</p>
            		<!-- <i class="fa fa-line-chart box-icon"></i> -->
			  </div>
		  </article></div></div>
	  <div class="col">

      <div class="container py-4">
		  <article class="postcard green3 green">
			  <div class="postcard__text ">
				  <h1 class="postcard__title green "><a href="#">Prototypes</a></h1>
				  <div class="postcard__bar"></div>
				  <p class="head-1">Prototypes</p>
            		<p class="number"><?php echo $prototypesCount ?> Total Prototypes</p>
            		<!-- <i class="fa fa-line-chart box-icon"></i> -->
			  </div>
		  </article></div></div>
	  <div class="col">

      <div class="container py-4">
		  <article class="postcard yellow3 yellow">
			  <div class="postcard__text ">
				  <h1 class="postcard__title yellow "><a href="#">DISCUSSIONS</a></h1>
				  <div class="postcard__bar"></div>
				  <p class="head-1">Discussions</p>
            		<p class="number"><?php echo $discussionsCount ?> Total Discussions</p>
            		<!-- <i class="fa fa-line-chart box-icon"></i> -->
			  </div>
		  </article></div></div>
	  <div class="col">

	  </div>

 </div>

 <div class="row ml-3 mr-3">
	
	<div class="col">
		<div class="dashboard2"> <a><i class="fa fa-table" aria-hidden="true"></i></a> USER TABLE</div>
	</div>
</div>

<div class="userTable">
 <div class="row ml-3 mr-3">
	
<div class="col">
<table class="table table-dark table-hover">
  <thead>
    <tr>
	<th scope="col">Full Name</th>
    <th scope="col">Email</th>
    <th scope="col">Total Experiment</th>
    </tr>
  </thead>
  <?php
   foreach ($allUsers as $row) {
      $totalExp = $currentAdmin->getAllExperiments($row['id']);
  echo '<tbody>
  	<tr data-href="../login.phtml">
          <td>'.$row['first_name'].'</td>
          <td>'.$row['email'].'</td>
          <td>'.$totalExp.'</td>
        </tr>
  </tbody>';
  }
  ?>
</table>
</div>
</div>


</div>







    <!-- jQuery CDN - Slim version (=without AJAX) -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <!-- Popper.JS -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>

    <!-- Bootstrap JS -->

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>



    <script type="text/javascript">

        $(document).ready(function () {

            $('#sidebarCollapse').on('click', function () {

                $('#sidebar').toggleClass('active');

            });

        });

    </script>
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const rows = document.querySelectorAll("tr[data-href]");

            rows.forEach(row => {
                row.addEventListener("click", () => {
                    window.location.href = row.dataset.href;
                });
            });
        });
    </script>






</div>
</body>

</html> 