<?php
require 'Views/Template/adminHeader.phtml';
?>
        <!-- Page Content  -->
<div id="content">





<!--
<div class="header body-background3">
<div class="d-flex justify-content-between">
    <div class="p-2 align-self-center">
<button type="button" id="sidebarCollapse" class="sidebutton-hover sidebutton">
                        <i class="fa fa-align-left"></i>
                        <span>Menu</span>
                    </button></div>
    <div class="p-2 align-self-center">
<a class="dashboard" >Admin Panel</a></div>
    <div class="p-2 align-self-center">
	 </div>
  </div>
</div>  
-->




<div class="row ml-3 mr-3 dashboard2">
	
	<div class="col float-lg-left">
		<div class=""> <a><i class="fa fa-table" aria-hidden="true"></i></a> User List</div>
	</div>
  <div class="col-md-auto">
    </div>
  <div class="col col-md-auto float-right ml-1 ">
  <form method="POST" class="form-inline">
  <div class="input-group ">
              <input type="text" class="form-control h-100" placeholder="Username" aria-label="Recipient's username" aria-describedby="basic-addon2" name="toSearch">
              <div class="input-group-append ">
    <button class="btn" type="submit" name="searchUsers"><i class="fa fa-search" aria-hidden="true"></i></button>
    </form>
  </div>
</div>
	</div>
</div>

<?php
  if($searchResults != 1){
    foreach($searchResults as $row)
    {
      echo '<br>';
      echo $row['first_name'];
    }
  }
  else {
    echo '<div class="alert alert-danger alert-dismissible d-flex align-items-center fade show">
                    <i class="bi-exclamation-octagon-fill"></i>
                    <strong class="mx-2">No Results matchin or conatining that word found!</strong>
              </div>';
  }
  ?>

<div class="userTable">
 <div class="row ml-3 mr-3">
	
<div class="col">
<table class="table table-dark table-hover">
  <thead>
    <tr>
	<th scope="col">Full Name</th>
    <th scope="col">Email</th>
    <th scope="col">Total Experiments</th>
    </tr>
  </thead>
  <?php
   foreach ($allUsers as $row) {
      $totalExp = $currentAdmin->getAllExperiments($row['id']);
  echo '<tbody>
  	<tr>
      
          <td>'.$row['first_name'].' '.$row['last_name'].'</td>
          <td>'.$row['email'].'</td>
          <td>'.$totalExp.'</td>
          <td><a href="userProfile.php?id=' . $row['id'] . '" class="btn-danger p-1">>>></a></td>
        </tr>
  </tbody>';
  }
  ?>
</table>
</div>
</div>


</div>













</div>
</body>

</html> 